import { describe, expect, it } from "vitest";
import { runCli } from "./index.js";

describe("framekit CLI", () => {
  it("generates SDK types from an app module path", async () => {
    let stdout = "";

    await runCli([
      "generate-sdk",
      "examples/crm/src/app.ts"
    ], {
      stdout: {
        write: (chunk: string | Uint8Array) => {
          stdout += String(chunk);
          return true;
        }
      },
      log: () => undefined
    });

    expect(stdout).toContain("export type CustomerInput");
    expect(stdout).toContain("export type DealWorkflowAction");
    expect(stdout).toContain('"win"');
  });

  it("generates migration files from app module paths", async () => {
    let stdout = "";

    await runCli([
      "generate-migration",
      "examples/crm/src/app.ts",
      "examples/crm/src/app.ts"
    ], {
      stdout: {
        write: (chunk: string | Uint8Array) => {
          stdout += String(chunk);
          return true;
        }
      },
      log: () => undefined
    });

    expect(stdout).toContain("Generated by framekit generate-migration");
    expect(stdout).toContain("export const migration");
    expect(stdout).toContain('"checksum"');
  });
});
