import type { AttachmentMetadata, ChildRecord, FieldDefinition } from "../domain/types";
import { exactDeskPattern } from "../validation/fields";

export function FieldInput({ field, value, onChange, canManageAttachments, onUpload, onDeleteAttachment }: { field: FieldDefinition; value: unknown; onChange: (value: unknown) => void; canManageAttachments?: boolean; onUpload?: (file: File) => void; onDeleteAttachment?: (id: string) => void }) {
  const domain = field.validators?.find((validator) => validator.kind === "domain"); const disabled = field.readOnly || Boolean(field.computed);
  if (field.type === "children") {
    const rows = Array.isArray(value) ? value as ChildRecord[] : [];
    const replace = (index: number, row: ChildRecord) => onChange(rows.map((candidate, candidateIndex) => candidateIndex === index ? row : candidate));
    const move = (index: number, offset: number) => { const next = [...rows]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target]!, next[index]!]; onChange(next); };
    return <div className="child-records">{rows.map((row, index) => <fieldset key={row.id ?? index}><legend>Row {index + 1}</legend>{(field.fields ?? []).map((child) => <label key={child.name}><span>{child.label}</span><FieldInput field={child} value={row.data[child.name]} onChange={(next) => replace(index, { ...row, data: { ...row.data, [child.name]: next } })} /></label>)}<div className="row-actions"><button type="button" aria-label={`Move row ${index + 1} up`} onClick={() => move(index, -1)}>↑</button><button type="button" aria-label={`Move row ${index + 1} down`} onClick={() => move(index, 1)}>↓</button><button type="button" onClick={() => onChange(rows.filter((_, candidateIndex) => candidateIndex !== index))}>Remove row</button></div></fieldset>)}<button type="button" aria-label="Add child row" onClick={() => onChange([...rows, { data: {} }])}>Add row</button></div>;
  }
  if (field.type === "attachments") { const attachments = Array.isArray(value) ? value as AttachmentMetadata[] : []; return <div className="attachments">{attachments.map((attachment) => <div key={attachment.id} className="attachment-row"><span>{attachment.name} · {attachment.size} bytes</span><button type="button" aria-label={`Delete ${attachment.name} attachment`} disabled={!canManageAttachments} onClick={() => onDeleteAttachment?.(attachment.id)}>Delete attachment</button></div>)}<input aria-label={`Upload ${field.label}`} type="file" disabled={!canManageAttachments} onChange={(event) => { const file = event.target.files?.[0]; if (file) onUpload?.(file); event.target.value = ""; }} />{!canManageAttachments ? <small>Save a draft before uploading files.</small> : null}</div>; }
  if (domain?.kind === "domain") { const selectedIndex = Math.max(0, domain.values.findIndex((option) => Object.is(option, value))); return <select value={String(selectedIndex)} onChange={(event) => onChange(domain.values[Number(event.target.value)])} disabled={disabled}>{domain.values.map((option, index) => <option key={`${typeof option}:${String(option)}`} value={String(index)}>{String(option)}</option>)}</select>; }
  if (field.type === "boolean") return <input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} disabled={disabled} />;
  if (field.type === "select") { const options = field.options ?? []; return <select value={String(value ?? options[0] ?? "")} onChange={(event) => onChange(event.target.value)} disabled={disabled}>{options.map((option) => <option key={String(option)} value={String(option)}>{String(option)}</option>)}</select>; }
  if (field.type === "long_text") { const length = field.validators?.find((validator) => validator.kind === "length"); return <textarea value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} disabled={disabled} minLength={length?.kind === "length" ? length.min : undefined} maxLength={length?.kind === "length" ? length.max : undefined} />; }
  const length = field.validators?.find((validator) => validator.kind === "length"); const range = field.validators?.find((validator) => validator.kind === "range"); const pattern = field.validators?.find((validator) => validator.kind === "pattern"); const exact = field.type === "decimal" || field.type === "currency";
  const patternValue = pattern?.kind === "pattern" ? ({ email: "[^@\\s]+@[^@\\s]+\\.[^@\\s]+", uuid: "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}", slug: "[a-z0-9]+(?:-[a-z0-9]+)*", alphanumeric: "[A-Za-z0-9]+" })[pattern.pattern] : undefined;
  return <input type={field.type === "number" ? "number" : "text"} inputMode={exact ? "decimal" : undefined} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} disabled={disabled} minLength={length?.kind === "length" ? length.min : undefined} maxLength={length?.kind === "length" ? length.max : undefined} min={field.type === "number" && range?.kind === "range" ? range.min : undefined} max={field.type === "number" && range?.kind === "range" ? range.max : undefined} pattern={exact ? exactDeskPattern(field) : patternValue} data-min={exact && range?.kind === "range" ? range.min : undefined} data-max={exact && range?.kind === "range" ? range.max : undefined} data-precision={exact ? field.precision ?? 18 : undefined} data-scale={exact ? field.scale ?? (field.type === "currency" ? 2 : 6) : undefined} />;
}
